# -*- coding: utf-8 -*-
"""test_algo_b_2_4_bis_traitement_unitaire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaSCiDZZGkU5KJjhxJXSyoJGJT_qOTJK
"""

import pandas as pd
import numpy as np
import pytest
from src.stan import read_and_process_file, convert_and_calculate
from src.algo_b_2_3_traitement_preliminaire import traitement_utile_inutile
from src.algo_b_2_4_bis_traitement_unitaire import traitement_unitaire

result = read_and_process_file("data/RDVC-20230522.pln")
result = convert_and_calculate(result)
result = traitement_utile_inutile(result)
result_utile = result[result["utile_inutile"] == "UTI"].copy()
result_utile_traitee = traitement_unitaire(result_utile)

def test_invalidite_NACT():
    invalidite = result_utile_traitee[result_utile_traitee["callSign_prevu"]=="TOM22B"]["invalidite_TU"].iloc[0]
    assert "NACT" in invalidite, "invalidite sans NACT"
