# -*- coding: utf-8 -*-
"""test_algo_b_2_3_traitement_preliminaire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaSCiDZZGkU5KJjhxJXSyoJGJT_qOTJK
"""

import pandas as pd
import numpy as np
import pytest
from src.stan import read_and_process_file, convert_and_calculate
from src.algo_b_2_3_traitement_preliminaire import traitement_utile_inutile

@pytest.fixture
def processed_data():
    raw_data = read_and_process_file("data/RDVC-20230522.pln")
    return convert_and_calculate(raw_data)

def test_traitement_utile_inutile(processed_data):
    # Impression des données traitées pour débogage ou inspection
    print("Affichage des données traitées:")
    print(processed_data)

    # Exécution de la fonction spécifique au traitement et impression des résultats
    result = traitement_utile_inutile(processed_data)
    print("Affichage du résultat du traitement:")
    print(result)

    # Assertions pour vérifier que tout fonctionne comme prévu
    assert not result.empty, "Le résultat ne doit pas être vide"
    # Vous pouvez ajouter d'autres assertions pour valider les données spécifiques

    # Optionnel: Imprimer des informations supplémentaires si nécessaire
    print("Test complété avec succès.")
    
result = traitement_utile_inutile(result)


def test_utile_vol_active_non_fictif():
    utilite = result[result["callSign_prevu"]=="TRA79Y"]["utile_inutile"].iloc[0]
    assert utilite == "UTI", "utilité diff de UTI"

def test_inutile_vol_fictif_avec_moins():
    utilite = result[result["callSign_prevu"]=="RFIN65"]["utile_inutile"].iloc[0]
    assert utilite == "FICT", "utilité diff de FICT"

def test_inutile_vol_annule():
    utilite = result[result["callSign_prevu"]=="THY90F"]["utile_inutile"].iloc[0]
    assert utilite == "CNL", "utilité diff de CNL"

def test_inutile_vol_centrefr():
    utilite = result[result["callSign_prevu"]=="TRA4N"]["utile_inutile"].iloc[0]
    assert utilite == "2SLF", "utilité diff de 2SLF"

def test_inutile_vol_circulaire():
    utilite = result[result["callSign_prevu"]=="FNY5118"]["utile_inutile"].iloc[0]
    assert utilite == "CIRC", "utilité diff de CIRC"

def test_utile_vol_tout_les_test_faux():
    utilite = result[result["callSign_prevu"]=="TOM22B"]["utile_inutile"].iloc[0]
    assert utilite == "UTI", "utilité diff de UTI"

def test_realise_pln_nan():
    utilite = result[result["callSign_prevu"]=="THY90F"]["utile_inutile"].iloc[0]
    assert utilite == "CNL", "utilité diff de CNL"

def test_realise_centre_nan():
    utilite = result[result["callSign_prevu"]=="UAL71"]["utile_inutile"].iloc[0]
    assert utilite == "2SLF", "utilité diff de 2SLF"

def test_creation_csv():
    result.to_csv('output/final_outputTP.csv', index=False)
