# -*- coding: utf-8 -*-
"""Creation_TABLES_SYSTEMES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkvdM_7qK7MV2PTaSt27HBRZeC91x3Qs
"""

import pandas as pd

INDICATIF_FICTIF = pd.read_csv("data/TABLE_SYSTEME/indicatifsfictifs", sep=';', skiprows=3)
EUROPE_SUD = pd.read_csv("data/TABLE_SYSTEME/payssud", sep=';', skiprows=3)
AERONEFS_DE_MOINS_DE_2_TONNES = pd.read_csv("data/TABLE_SYSTEME/aeronefsmoin2tonnes", sep=';', skiprows=3)
INDICATEURS_D_EMPLACEMENT_FAUX = pd.read_csv("data/TABLE_SYSTEME/aerodromesfaux", sep=';', skiprows=3)
AERODROME_A_VERIFIER = pd.read_csv("data/TABLE_SYSTEME/aerodromesaverifier", sep=';', skiprows=3)
AERODROMES_D_APPROCHE = pd.read_csv("data/TABLE_SYSTEME/aerodromesapproche", sep=';', skiprows=3)
AERODROMES_FRONTALIERS = pd.read_csv("data/TABLE_SYSTEME/aerodromesfrontaliers", sep=';', skiprows=3)
INDICATIF_A_CODE_AUTO = pd.read_csv("data/TABLE_SYSTEME/indicatifscodesauto", sep=';', skiprows=3)
INDICATIFS_A_STRUCTURE_TRIGRAMME_CORRECTE = pd.read_csv("data/TABLE_SYSTEME/structurtrigrammecorrects", sep=';', skiprows=3)
COMPAGNIES_BIGRAMMES_ET_SUFFIXES = pd.read_csv("data/TABLE_SYSTEME/cgniebigrammesetsuffixes", sep=';', skiprows=3)
COMPAGNIES_AVEC_TRIGRAMME = pd.read_csv("data/TABLE_SYSTEME/compagniesavectrigrammesautorise", sep=';', skiprows=3)
INDICATIFS_TRIGRAMME_A_VERIFIER = pd.read_csv("data/TABLE_SYSTEME/structuretrigrammeverif", sep=';', skiprows=3)
LETTRES_AIR_FRANCE = pd.read_csv("data/TABLE_SYSTEME/lettresairfrance", sep=';', skiprows=3)
LETTRES_AIR_FRANCE = LETTRES_AIR_FRANCE[~((LETTRES_AIR_FRANCE['Lettre'].str.contains("MODIFIE", na=False)) & (LETTRES_AIR_FRANCE['Code exo/trait'].isna()) & (LETTRES_AIR_FRANCE['Commentaire'].isna()))]
LETTRES_AIR_FRANCE.reset_index(drop=True, inplace=True)
IMMATRICULATION_A_VERIFIER = pd.read_csv("data/TABLE_SYSTEME/immataverif", sep=';', skiprows=3)
IMATRICULATION_CORRECTE = pd.read_csv("data/TABLE_SYSTEME/immatcorrectes", sep=';', skiprows=3)
OPERATEURS_MILITAIRES = pd.read_csv("data/TABLE_SYSTEME/oprmili", sep=';', skiprows=3)
AERONEFS_STRICTEMENT_MILITAIRES = pd.read_csv("data/TABLE_SYSTEME/aeronefmilitaire", sep=';', skiprows=3)
