name: RDVC application

on:
  push:
    branches: [ main ]
    paths:
        - 'src/**'
        - 'test2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Build Environment
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lecture_stan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Test Environment
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests for lecture_stan
        run: pytest -v --output=data/RDVC-20230522.pln test2/test_algo_decodage.py -s

  traitement_preliminaire:
    runs-on: ubuntu-latest
    needs: lecture_stan
    steps:
      - name: Setup Test Environment
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests for traitement_preliminaire
        run: pytest -v test2/test_algo_b_2_3_traitement_preliminaire.py --output="data/RDVC-20230522.pln" -s

  traitement_pln_utile:
    runs-on: ubuntu-latest
    needs: traitement_preliminaire
    steps:
      - name: Setup Test Environment
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests for traitement_pln_utile
        run: pytest -v --output=data/RDVC-20230522.pln test2/test_algo_b_2_4_bis_traitement_unitaire.py -s
