name: RDVC application

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lecture_stan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate and save DataFrame head
        run: |
          python -c "
          import pandas as pd
          from datetime import datetime, timedelta
          from src.stan import read_and_process_file, convert_and_calculate
          output = read_and_process_file('data/RDVC-20230522.pln')
          output = convert_and_calculate(output)
          output.head().to_csv('output/head.csv', index=False)"
        shell: bash

      - name: Upload DataFrame head as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: dataframe-head
          path: output/head.csv

  traitement_preliminaire:
    runs-on: ubuntu-latest
    needs: lecture_stan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download DataFrame head from artifact
        uses: actions/download-artifact@v2
        with:
          name: dataframe-head

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Display the DataFrame head
        run: cat head.csv

  traitement_pln_utile:
    runs-on: ubuntu-latest
    needs: traitement_preliminaire
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run tests
        run: pytest -v test2/test_algo_b_2_4_bis_traitement_unitaire.py -s
