name: RDVC application

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  build:  # Sets up the environment and installs dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required Python packages

  lecture_stan:  # Job to run specific tests after building
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test-set: ['installdependencies', 'test', 'stan3']
    steps:
      - name: Setup and Run lecture_stan tests
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        if: ${{ matrix.test-set == 'installdependencies' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Specific Tests
        if: ${{ matrix.test-set == 'test' }}
        run: pytest -v --output=data/RDVC-20230522.pln test2/test_algo_decodage.py -s

  traitement_preliminaire:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after 'build'
    strategy:
      matrix:
        test-set: ['set1', 'set2', 'set3']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        if: ${{ matrix.test-set == 'set1' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        if: ${{ matrix.test-set == 'set2' }}
        run: pytest -v test2/test_algo_b_2_3_traitement_preliminaire.py --output="data/RDVC-20230522.pln" -s

  traitement_pln_utile:
    runs-on: ubuntu-latest
    needs: [traitement_preliminaire, lecture_stan]  # Waits for both these jobs to complete
    strategy:
      matrix:
        test-set: ['install', 'test']
    steps:
      - name: Setup Test Environment
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        if: ${{ matrix.test-set == 'install' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests for traitement_pln_utile
        if: ${{ matrix.test-set == 'test' }}
        run: pytest -v --output=data/RDVC-20230522.pln test2/test_algo_b_2_4_bis_traitement_utile.py -s
