name: RDVC application

on:
  push:
    branches: [ main ]
    paths:
        - 'src/**'
        - 'test2/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  lecture_stan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests or process data
        run: |
          pytest -v test2/test_algo_decodage.py -s
          # Assume this generates some output files you need in 'output/' directory

      - name: Upload result artifact
        uses: actions/upload-artifact@v2
        with:
          name: lecture-stan-artifacts
          path: output/  # Make sure this path points to the output files generated by this job

  traitement_preliminaire:
    runs-on: ubuntu-latest
    needs: lecture_stan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download result artifact from lecture_stan
        uses: actions/download-artifact@v2
        with:
          name: lecture-stan-artifacts

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run processing or tests using the downloaded artifacts
        run: |
          pytest -v test2/test_algo_b_2_3_traitement_preliminaire.py -s
          # Additional commands can be added here to use the downloaded artifacts

  traitement_pln_utile:
    runs-on: ubuntu-latest
    needs: traitement_preliminaire
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Run tests
      run: pytest -v test2/test_algo_b_2_4_bis_traitement_unitaire.py -s
